// <auto-generated />
namespace NCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewRwquestDrugs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewRwquestDrugs));
        
        string IMigrationMetadata.Id
        {
            get { return "201901271422181_NewRwquestDrugs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
